// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVVPiHK6trY9B3s_Wxe6c2yM4h8N-ms9w',
    appId: '1:217568153905:web:3fa13db3bd0ce5d2eba010',
    messagingSenderId: '217568153905',
    projectId: 'flutterapp-77678',
    authDomain: 'flutterapp-77678.firebaseapp.com',
    storageBucket: 'flutterapp-77678.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8a8s5EpOjr7-rOoMwZciZs0i4QfPoyQk',
    appId: '1:217568153905:android:81ccb8f5ecd739a1eba010',
    messagingSenderId: '217568153905',
    projectId: 'flutterapp-77678',
    storageBucket: 'flutterapp-77678.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACVrOj-Ar9JFNuQ7omv8II0H6HF25IUPk',
    appId: '1:217568153905:ios:90b9e012ca6715c8eba010',
    messagingSenderId: '217568153905',
    projectId: 'flutterapp-77678',
    storageBucket: 'flutterapp-77678.firebasestorage.app',
    iosBundleId: 'com.example.fitgenius',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACVrOj-Ar9JFNuQ7omv8II0H6HF25IUPk',
    appId: '1:217568153905:ios:90b9e012ca6715c8eba010',
    messagingSenderId: '217568153905',
    projectId: 'flutterapp-77678',
    storageBucket: 'flutterapp-77678.firebasestorage.app',
    iosBundleId: 'com.example.fitgenius',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVVPiHK6trY9B3s_Wxe6c2yM4h8N-ms9w',
    appId: '1:217568153905:web:645928aa905c90b9eba010',
    messagingSenderId: '217568153905',
    projectId: 'flutterapp-77678',
    authDomain: 'flutterapp-77678.firebaseapp.com',
    storageBucket: 'flutterapp-77678.firebasestorage.app',
  );
}
